### ISSUE TITLE
what will we be using in this workshop? 

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/git#13]
Somewhere between examples.md and command-line.md, it would be useful to hear what tools will be used during the session. Something like "In this session, we'll be using the command line (terminal, bash) from the Command Line workshop. We'll also use your text editor and your browser. We'll be moving between these three spaces throughout the workshop. You may want to use (command + tab) or (ctrl + tab) to move quickly between the three windows on your desktop." 

This reinforces prior learning, and helps students to solidify the idea that there's a difference between the terminal, text editor, and browser.

**Comment by pswee001** [comment]
added at top of command-line.md
