### ISSUE TITLE
Revise abstract for clarity

### ISSUE THREAD

**Issue by hackettka** [DHRI-Curriculum/git#23]
Emphasize that these are two different tools. Position GitHub as one cloud-based platform among many.

**Comment by kallewesterling** [comment]
I think this sounds marvelous, @hackettka! I know this workshop in particular has been a little confusing for the DHRI Community Leaders for that reason. A good abstract might be great to set people's sailing clear from the get-go.

I also think that you could move the final paragraph into the `## Resources` section:

> To complete this workshop, you will need to have VS Code and Git installed on your local machine. If you have not installed them already, follow this link to instructions for VS Code, and this link to instructions for Git.

**Comment by kallewesterling** [comment]
I have been looking over the projects, and decided that we'll relay this to the next sprint. You have enough to do before Friday, I think! :) For now, just move the abstract the way it stands into the new files, and then we will revise in `sprint 2`. Thank you!
