### ISSUE TITLE
Draft learning objectives

### ISSUE THREAD

**Issue by hackettka** [DHRI-Curriculum/git#24]
None in version 1.0.

**Comment by kallewesterling** [comment]
If you could quickly go through the lessons and list the lessons learned in v.1.0 for this sprint, that would be great. A good example of what I think the git workshop's learning objectives should look like can be found in [the command-line's `frontmatter.md`](https://github.com/DHRI-Curriculum/command-line/blob/v2.0-smorello-edits/frontmatter.md)

**Comment by hackettka** [comment]
Done!
