### ISSUE TITLE
Prereqs

### ISSUE THREAD

**Issue by hackettka** [DHRI-Curriculum/git#25]
Should we include "Intro to Platforms" as a placeholder?

**Comment by kallewesterling** [comment]
Not sure what Intro to platforms is, but I think that the command line should, at least, be a prerequisite for this workshop, right @lmrhody ?

**Comment by hackettka** [comment]
Platforms is beyond the base group of classes we're starting with here so I've removed it, but if we decide to include that course, it would be good to add it here given that GitHub is a platform.

**Comment by kallewesterling** [comment]
I see - is that the one that's about web hosting and all of that?
