### ISSUE TITLE
Other tutorials

### ISSUE THREAD

**Issue by hackettka** [DHRI-Curriculum/git#28]
More could be added. This section is a bit weak compared to the others.

**Comment by kallewesterling** [comment]
A couple of good links:

- GitHub's nice "learning-center" pages/hubs: https://try.github.io/ and https://lab.github.com/
- I have also found Atlassian's tutorials good (https://www.atlassian.com/git/tutorials) but they are putting a lot of refs in to Bitbucket which might be confusing to an early learner
- This is an interactive "command line" tutorial with a visual representation, that is real good too: https://learngitbranching.js.org/

**Comment by kallewesterling** [comment]
This seems to relate to https://github.com/DHRI-Curriculum/git/issues/44 so I'm going to go ahead and close this issue, and then it will still be linked in the thread over at the new (finalizing this file) issue.
