### ISSUE TITLE
Add resources on branching and merging

### ISSUE THREAD

**Issue by hackettka** [DHRI-Curriculum/git#33]

**Comment by hackettka** [comment]
revisit in text once added to adjust as needed - "Coauthored pubs"

**Comment by kallewesterling** [comment]
I assigned you, just since I wasn't sure what this was referring to! (So assumed it was one of your todo-items!) :)

**Comment by kallewesterling** [comment]
Hi @hackettka — just wanted to check in what the status is on this issue?

**Comment by hackettka** [comment]
I'm going to close it out. After a closer review, I think I have resources that speak to this already.

**Comment by kallewesterling** [comment]
Great, thank you!
