### ISSUE TITLE
Create glossary term files from git

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/git#45]
- [x] Go through `lessons.md` (and other files) and find all important terms in need of definition to help learners grasp concepts, tools, commands, etc. List the files in a text file, or keep them in this issue feed below, for instance.

- [x] Add a file to the glossary repository's [`terms`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms) folder called `<term>.md` for each of the terms.

   - [How do I add terms to the glossary?](https://github.com/DHRI-Curriculum/glossary/blob/v2.0/how-to-add-new-terms.md) <— See instructions

**Comment by hackettka** [comment]
Additional terms that could be added - not specific to the lesson: 

Digital Humanities
Learning management system
Command line
Terminal
Plain text file
Markup language
Local machine / work locally
Web browser
Flag
WordPress
Leaflet
Directory
Attribution

**Comment by kallewesterling** [comment]
Thank you, @hackettka, for adding these terms here. I think this list will be very useful for the future development of the glossary part of the website!

**Comment by kallewesterling** [comment]
If you are done with the terms, please see and address this issue: https://github.com/DHRI-Curriculum/glossary/issues/37.
